apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: default
spec:
  replicas: 2
  selector:
     matchLabels:
        app: myapp
  template:
    metadata:
      labels: 
         app: myapp
    spec:
      containers:
      - image: 806819308050.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
        name: myapp
        ports:
        - containerPort: 3000
