apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
     - image: 806819308050.dkr.ecr.us-east-1.amazonaws.com/myapp:latest
       name: myapp
       ports:
       - containerPort: 3000
